name: nirbhaya
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  flutter_phone_direct_caller: ^2.1.1
  font_awesome_flutter: ^8.4.0
  animated_text_kit: ^4.2.1
  flutter_otp_text_field: ^1.1.0+2
  firebase_core: ^2.4.0
  pinput: ^2.2.20
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  telephony: ^0.2.0
  geolocator: ^9.0.2
  fluttertoast: ^8.1.2
  geocoding: ^2.0.5
  firebase_database: ^10.0.8
  gradient_borders: ^0.2.0
  http: ^0.13.5
  google_maps_flutter: ^2.2.2
  flutter_sms: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
